### ISSUE TITLE
add support for configurable loading delay

### ISSUE THREAD

**Issue by philippd** [philippd/angular-deferred-bootstrap#2]
make it possible to set a delay for adding the 'loading' css class to the body -> it should not show if initializing takes less than X ms

**Comment by nbarbettini** [comment]
I've added this functionality (and some other tweaks) and would be happy to submit a pull request if you'd like. Here's my code: https://github.com/nbarbettini/angular-deferred-bootstrap/blob/master/src/deferred-bootstrap.js

The new config items are:
`beforeLoading`: simple callback that is fired before the loading process starts
`afterLoading`: simple callback that is fired after the loading is finished, before bootstrapping
`onLoadingShow`: callback that is fired as the loading class is being applied. If the callback returns a Promise, wait for it to be resolved before continuing.
`onLoadingHide`: Same as above, when the loading class is removed.
`onErrorShow`: Same as above, when the error class is added.
`showLoadingThreshold`: If the loading process takes less than this (in ms), the loading class and any callbacks will be skipped.
`showLoadingMinDuration`: If the loading process takes longer than `showLoadingThreshold`, ensure that the loading class remains on the page for at _least_ this long (in ms).
`maxLoadingTimeout`: Assume the loading process failed and apply the error class if it takes longer than this (in ms). Ignored if zero.

I'm using `onLoadingShow` and `onLoadingHide` to allow me to do some additional UI work in addition to the class being set on the page.

Here's how it could be used: 
```javascript
window.deferredBootstrapper.bootstrap({
	element: window.document,
	module: 'app',
	resolve: {
		MYCONFIG: ['$timeout', function ($timeout) {
			var deferred = $q.defer();
			$timeout(function () { deferred.resolve({ online: true }) }, 4000);
			return deferred.promise;
		}]
	},
	onLoadingShow: window.progressStart,
	onLoadingHide: window.progressFinished,
	onErrorShow: window.loadingError,
	showLoadingThreshold: 500,    //ms
	showLoadingMinDuration: 1500, //ms
	maxLoadingTimeout: 60000,     //ms
});
```
