### ISSUE TITLE
Improve docs on testing

### ISSUE THREAD

**Issue by bmcorser** [philippd/angular-deferred-bootstrap#28]
This project looks great, but I'm having difficulty mocking the constants in testing. We're using whatever test setup that comes with Yeoman's Angular generator.

How should I be setting up a "global `beforeEach()`"?

I've added the code provided in docs to `test/spec/global.js`, but it errors out about the `module` call:

```
ReferenceError: Can't find variable: module
```

Cheers,

Ben

**Comment by philippd** [comment]
I just created a new project using the yeoman generator, created a new ```test/spec/global.js``` file with the following content and it worked as expected.

```javascript
beforeEach(function () {
  module(function ($provide) {
    $provide.constant('APP_CONFIG', { someUrl: '/dummyValue' });
  });
});
```

It seems that in your setup ```angular-mocks.js``` is not loaded in the karma configuration. Make sure you have it in ```test/karma.conf.js``` and that it's listed before ```test/spec/**/*.js```: 

```javascript
files: [
      'bower_components/angular/angular.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'bower_components/angular-animate/angular-animate.js',
      'bower_components/angular-cookies/angular-cookies.js',
      'bower_components/angular-resource/angular-resource.js',
      'bower_components/angular-route/angular-route.js',
      'bower_components/angular-sanitize/angular-sanitize.js',
      'bower_components/angular-touch/angular-touch.js',
      'app/scripts/**/*.js',
      'test/mock/**/*.js',
      'test/spec/**/*.js'
    ],
```

**Comment by bmcorser** [comment]
Thanks, I got there too .. came back to the issue to close it.

I do still see a 404 when I run the test suite, despite my mocked constants being available in code under test. Did you think about the approach of using `$httpBackend` to mock the server response for a `GET` on `/config.json` or similar?

**Comment by philippd** [comment]
It depends on what you want to test.

If you don't plan to test the bootstrapping part, you can just exclude the file where the ```deferredBootstrapper```is used in the ```karma.conf.js``` and use the approach described above. This mocks the loading of the initial data completely and you will see no 404 anymore when running the tests.

If you want to test the bootstrapping code, you could set up the ```$httpBackend``` in a global ```beforeEach()```. I have not done this in one of my projects, but it should work as well.
