### ISSUE TITLE
Removing 'deferred-bootstrap-error' class on re-initialize

### ISSUE THREAD

**Issue by vanthoom** [philippd/angular-deferred-bootstrap#32]
Hi,

if a error occured the 'deferred-bootstrap-error' class is added to the body tag. If I retrigger the application instantiation the class is not removed. Means if the application is startet and the body contains the class it should be removed to have a clean state if the application startup was working at the second try.

**Comment by marcusvetter** [comment]
+1

**Comment by philippd** [comment]
I'll fix it and release a new version.

**Comment by philippd** [comment]
released in 0.1.6, will be available via bower/npm in a second

**Comment by vanthoom** [comment]
cool thanks
