### ISSUE TITLE
Browser's back button is broken - Incompatibility with angular's ui-router

### ISSUE THREAD

**Issue by timothydang** [philippd/angular-deferred-bootstrap#38]
There might be an issue with `angular-deferred-bootstrap` and ui-router / angular's html5Mode. We have noticed that the browser's back button is no longer working as it always explicitly redirects you back to your original page you have come from, not the previous intended page.

- Using `$locationProvider.html5Mode(true);` or `$locationProvider.html5Mode(false);` doesn't seem to fix the issue. 

- When hitting back button, both `$locationChangeSuccess` and `$stateChangeStart` events incorrectly shows page's original url as the "ToState" (not the previous state as we wanted it to) so there must have been something being intercepted and rewritten inside $stateProvider / $locationProvider

**Comment by philippd** [comment]
I don't see how this might be caused by ```angular-deferred-bootstrap```.

Please  provide a sample app showing the described behaviour.
