### ISSUE TITLE
Adding CommonJS/AMD support has broken webpack compilation

### ISSUE THREAD

**Issue by RShackleton** [philippd/angular-deferred-bootstrap#41]
Version v0.1.8 (#40) has caused webpack compilation to break. The error message received is below:

```
ERROR in ./~/angular-deferred-bootstrap/angular-deferred-bootstrap.js
Module not found: Error: Cannot resolve module 'deferredBootstrapper' in C:\...\node_modules\angular-deferred-bootstrap
 @ ./~/angular-deferred-bootstrap/angular-deferred-bootstrap.js 186:2-56
```

**Comment by philippd** [comment]
Any idea how this could be fixed? It crashes on the line we try to define the module:

```javascript
if (typeof define === 'function' && define.amd) {
  define(['deferredBootstrapper'], deferredBootstrapper);
}
````

@D34THWINGS do you know what might go wrong here?

**Comment by D34THWINGS** [comment]
I was too quick on this one, I'll make a PR to rectify this. The define is trying to import deferredBootstrapper module wich does not exist, instead it should be `define([], deferredBootstrapper);`

**Comment by philippd** [comment]
Thanks @D34THWINGS, will be released in a few minutes...
